server:
  port: 80
  servlet:
    session:
      cookie:
        name: sid
      timeout: 1d
logging:
  file:
    path: log
    max-history: 30

spring:
  datasource:
    url: jdbc:h2:~/.neplog/neplog
    username: neplog
    password: neplog
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  h2:
    console:
      enabled: true
  data:
    redis:
      repositories:
        enabled: false
  profiles:
    active: dev

neplog:
  file:
    root: [.neplog, uploads]
    # 必须以'/'开头
    virtual: /uploads
    options:
      avatar: {path: [img], type: avatar, maxSize: 3,thumbnail: true, width: 200, height: 200}
      cover: {path: [img], type: cover, maxSize: 3}
      image: {path: [img], type: image, maxSize: 3}
      file: {path: [common], type: file, maxSize: 30}

  security:
    secret: j.2_d?+bn
    AESKey: I8KI6i+3UhXVd02N
    captcha-prefix: captcha
    token-expire-time: 24
    token-refresh-time: 2
    reset-password: false

  seo:
    sitemap:
      enabled: true
      base-url: https://neptu.cn
      target-folder: .

