server:
  port: 80
  servlet:
    session:
      cookie:
        name: sid
      timeout: 1d
logging:
  file:
    path: log
    max-history: 30

spring:
  datasource:
    url: jdbc:h2:~/.neplog/neplog
    username: neplog
    password: neplog
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB
  h2:
    console:
      enabled: true
  data:
    redis:
      repositories:
        enabled: false

neplog:
  file:
    root: .neplog/uploads
    virtual: /uploads
    options:
      avatar: {path: [img], thumnail: true, width: 200, height: 200}
      articleCover: {path: [img]}
      image: {path: [img]}
      file: {path: [common]}

  security:
    secret: j.2_d?+bn
    AESKey: I8KI6i+3UhXVd02N
    captcha-prefix: captcha
    token-expire-time: 24
    token-refresh-time: 2
